  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/welcome/"

  [[main]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "CV"
  weight = 400
  identifier = "CV"
  url = "AlexKwongCV_April22.pdf"

  [[main]]
  name = "Posts"
  weight = 500
  identifier = "posts"
  url = "/post/"
  
  [[main]]
  name = "Google Scholar"
  weight = 500
  identifier = "google scholar"
  url = "https://scholar.google.com/citations?user=F-sGJEIAAAAJ&hl=en"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"